import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
         <header className="flex justify-between items-center h-44 bg-gray-100">
          <h1>LOGO</h1>      
          <div> 
              <Link href="/signin">Logga in</Link>
         </div>
         </header>
        {/* Här renderas innehållet i vår page.tsx */}
        {children}
        <footer className="row-start-3 flex gap-6 flex-wrap items-center justify-center">
      
         <p>Copy copy Sandra</p>    
        
      </footer>
      </body>
    </html>
  );
}
